# -*- coding: utf-8 -*-
"""10 Maret 2026

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hcPH_BNIV8apITKogUckl5elJBGPLaQ3
"""

template = "halo saya %a dari %a"
print(template %('fikry aja','Kamboja'))

nama = 'Muhammad Ahmad'
asal = 'Kamboja'

print (f'Perkenalkan saya {nama} dari {asal}')

alamat = 'Bandung, jawabarat, papua'

print(alamat.split())
print(alamat.split(','))
print(alamat.split(', '))

"""MEMECAH STRING"""

print('!'.join(['kamu','gak','suka']))

print('halo kamu orang aneh!'.upper())
print('halo kamu orang aneh!'.lower())
print('halo kamu orang aneh!'.title())
print('Halo Kamu Orang Aneh!'.swapcase())

angka = '67890'

print('Index angka 8:', angka.find('8'))
print('Index angka 89:', angka.find('89'))
print('Index angka 33:', angka.find('33'))

asal = 'Kamojao'

print(asal.find('o'))
print(asal.find('ja'))

"""mereplace kata sting"""

ibu_kota = 'Negara'

print(ibu_kota.replace('a','o'))
print(ibu_kota.replace('ra','bo'))
print(ibu_kota.replace('a',''))

"""menghitung jumlah karakter"""

paragraf = 'Dari kemaren ini banyak ditemukan kasus pelecehan'
x = paragraf.count("ni")

print(f'Kata "ni" muncul sebanyak {x} kali')