# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BTnptOMNAdlfLpPBmEi_J8j-Q69YAvmm
"""

nama = 'Muhammad Fikry'
asal = 'bandung'

print (nama)

print (asal)

print (nama + asal)

print ('Halo, nama saya', nama)

print ('halo, nama saya', nama, 'asal saya dari', asal)

data_lengkap_banget_fix_final = nama, asal

print (data_lengkap_banget_fix_final)

"""**STRING + NO STRING**"""

asal_kota = 'bandar bandung'
kode_pos = 45171

asal_kota_kode_pos = asal_kota + str(kode_pos)

print (asal_kota_kode_pos)

asal_kota_x3 = asal_kota * 3

print (asal_kota_x3)